language: ruby

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE chitter_test;'
  - psql -U postgres -c 'CREATE TABLE peeps(id SERIAL PRIMARY KEY, post_time TIME, message VARCHAR(140), username VARCHAR(50));'

script:
  - bundle exec rspec
